### ISSUE TITLE
add option to disable minification

### ISSUE THREAD

**Issue by aleemb** [retyui/clean-css-loader#14]
It would be very useful to have an option to disable minification for dev and other use-cases:

```
loader: "clean-css-loader",
  options: {
    minification: false
  }
}
```

**Comment by aleemb** [comment]
To clarify, I would like to run the level 1 and even some level 2 optimisations but would like to disable only the minification aspect for legibility and testing.

**Comment by retyui** [comment]
New PR(pull request) welcome

**Comment by retyui** [comment]
Please use a `process.env.NODE_ENV`  (or whatever `process.env.DISABLE_CLEAN_CSS`) to exclude loader from pipe of css loaders

See more: https://github.com/retyui/clean-css-loader#via-webpack-config-recommended
