### ISSUE TITLE
Not working with extract-text plugin

### ISSUE THREAD

**Issue by hworld** [retyui/clean-css-loader#4]
In webpack 2.

```
Child extract-text-webpack-plugin:

    ERROR in ./~/css-loader?-minimize!./~/clean-css-loader!./~/postcss-loader!./~/vue-template-loader/lib/scoped-style-loader.js?id=data-v-13!./~/stylus-relative-loader?paths[]=src/&resolve url&include css!./src/app/components/shell/top-nav/top-nav.s
tyl
    Module build failed: TypeError: Cannot read property 'cleancss' of undefined
        at Object.module.exports (.../node_modules/clean-css-loader/index.js:7:25)
```

All I'm doing is including it in the "use" option that includes the loaders. I tried it with and without options.

**Comment by retyui** [comment]
@hworld Could you provide a test case with an error?)

**Comment by hworld** [comment]
@retyui not sure if this will work for you, but you can try https://github.com/gamejolt/sites-io/tree/clean-css-loader
I put the changes for my repo into a branch. You'll have to:
- clone it
- git submodule init
- git submodule update
- npm i
- npm run build

The relevant webpack building code is here: https://github.com/gamejolt/frontend-lib/blob/f3bb056a81ce0b0992e5778a813eba017518198b/gulp/tasks/webpack.js

**Comment by retyui** [comment]
@hworld  Please check, `npm i -D clean-css-loader@0.0.5`

**Comment by hworld** [comment]
Aha! Seems to be working now! Thanks for the fix. I didn't expect it to be so fast. =]
