### ISSUE TITLE
Minify by default

### ISSUE THREAD

**Issue by stereokai** [retyui/clean-css-loader#5]
Great loader! Thank you.

I think it would be good to add a note in README that this loader minifies by default (for now).

An ideal solution would be to not minify by default, and allow setting that explicitly (same like css-loader).

Cheers!

**Comment by retyui** [comment]
Yes, that's a good idea!
Can send pull request?

**Comment by stereokai** [comment]
Yeah sure. I am also working on enabling your loader to work with a chained sourcemap. Like: `sass-loader -> clean-css-loader`

**Comment by stereokai** [comment]
@retyui Update: https://github.com/jakubpawlowicz/clean-css/issues/931

Please join the discussion :)
